### ISSUE TITLE
Add Processors

### ISSUE THREAD

**Issue by husamAwadhi** [husamAwadhi/power-parser#3]
To add new blueprint element which can help in casting/formatting parsed values

Cast types
1. bool-strict: `true` if value = `true`, `1`, `"true"`
2. bool: `false` if has value and != `true` if value = `true`, `1`, `"true"`
3. int: php casting
4. float: php casting

example: 
```yml
blueprint:
- fields:
      - name: cash
        position: 1
        type: int
```

Formatting
1. money
2. string length limits
```yml
blueprint:
- fields:
      - name: cash
        position: 1
        format: f%2 # input: 23.441 output: 23.44
      - name: cash
        position: 1
        format: s%5 # input: 'sweets' output: 'sweet'
```
